services:
  db:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dictionary
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - webnet

  web:
    image: englishweb
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SECRET_KEY1: django-insecure-a5fat&55q85&9z&gdiqky(l62tvv-^c$ik4=5*#t6i34rf!j#i
      DEBUG_MODE1: True
      HOST: db
      PORT: 3306
      NAME: dictionary
      USER: mat
      PASSWORD: megachlen
    networks:
      - webnet
    restart: always

#  nginx:
#    image: nginx:alpine
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./static:/site_settings/static
#    depends_on:
#      - web
#    networks:
#      - webnet
#
#  redis:
#    image: redis:alpine
#    networks:
#      - webnet

networks:
  webnet:

volumes:
  mysql_data:
