# Generated by Django 5.1.2 on 2024-10-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=500)),
                ('topic', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'words',
                'managed': True,
            },
        ),
    ]
